### ISSUE TITLE
remotes::install_github("bowmanr/scDNA",force=TRUE) installs version 1.0.1, not 1.1

### ISSUE THREAD

**Issue by robin-sto** [bowmanr/scDNA#11]
Hello,

I tried to install the newer version using your command above but it only reinstalls the existing version 1.0.1.  How can I get the newer version to install?

Thanks.

**Comment by namwob44** [comment]
Hi,
I think this is a mistyped spelling on our part with the build. Currently, if you are able to see any of the functions GetStainIndex(), GetMembership(), cell_confidence_labeling(), trajectory_of_interest_BSCITE_format(), then you have the latest version.  We will look into correcting the naming
