### ISSUE TITLE
locate .h5 file

### ISSUE THREAD

**Issue by gupta567varun** [bowmanr/scDNA#8]
Hi
I am trying to use this package and was wondering whether the repository comes with a .h5 file as shown in the Vignettes

Sample1962.dna+protein.h5

Hope to hear from you.

Regards,
Varun

**Comment by namwob44** [comment]
Hi Varun,

So we used to have it in the package, but have moved it from our package so it takes up less space to install/download. We have made a dataset available on google drive. It should be located for download here: [LAMA](https://drive.google.com/file/d/1eCW5a3zStpmbtfQVC6jpIf9hBxvZLh1p/view?usp=sharing)

Note the file name is changed and your vignette may need to change accordingly. We have updated the vignette file to immediately use this new available file.

Let me know if there is anything else.
