### ISSUE TITLE
Script Ends abruptly without producing any plots

### ISSUE THREAD

**Issue by MithunSarangdhar** [bowmanr/scDNA#9]
Hello Dr. Bowman,

Hope this email finds you well. I am, Mithun Sarangdhar, a research fellow at Cincinnati Children's Hospital and a close associate of Dr. Linde Miles. We have been working on mission bio’s tapestri analysis and were directed by Dr. Miles to use your script. I have been trying to run the script, but it pauses with some errors. I am new to R and do not have expertise in troubleshooting the script. We were wondering if you could identify the error that we are facing and possibly give some pointers to fix it.

So, just to give a bit of clarity, I go to your page and copy the codes from your page and run it on OnDemand RStudio. I can load the package; I am also able to load the files by setting up the working directory. But as I start with the script, it sends errors /halts in between. I am also not able to see any plots as well. I was wondering if you could just glance through the script.

 
 
I just copy those codes, change my file directory to my desired file location and press enter.

 
![image](https://github.com/user-attachments/assets/1dca23a2-4ca6-4fc9-8daf-3aad17e2dc03)

 
After the second set of commands for genes of interest (in blue), it doesn’t do anything. It just stops after that. Even if I try to see the clonograph, it doesn’t show me anything.
 
It would be very helpful if you could give me some insight on this error. 
 
Any help will be greatly appreciated.
 
Thank you.

Regards,
Mithun

**Comment by namwob44** [comment]
Posting fix for future people running into the same problem. Be sure to run our vignette as an RMD file instead of loading it in as an R script. If clonograph doesn't run in the console, you may need to look at the plots window on the bottom right panel, or activate quartz() to have another window appear in Rstudio! This way plots will show up for you. Closing issue for now.
